B = ord('B')
C = ord('C')
b = ord('b')
c = ord('c')
d = ord('d')
zero = ord('0')
one = ord('1')
two = ord('2')
dollar_sign = ord('$')
star_sign = ord('*')
addition_sign = ord('+')
space = ord(' ')

print("B = ", B)
print("C = ", C)
print("b = ", b)
print("c = ", c)
print("d = ", d)
print("0 = ", zero)
print("1 = ", one)
print("2 = ", two)
print("$ = ", dollar_sign)
print("* = ", star_sign)
print("+ = ", addition_sign)
print("Space character = ", space)

